repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.5
  hooks:
    - id: ruff
      args: ["--fix"]
    - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-private-key

- repo: local
  hooks:
    - id: pytest
      name: Run python tests
      entry: pytest src/test.py
      language: system
      files: \.txt$
