artifact_location: /Users/enzobergamini/Documents/cours/tps3A/mlops/SMART-PROJECT/runs/mlflow/547524966277708424
creation_time: 1739294443914
experiment_id: '547524966277708424'
last_update_time: 1739294443914
lifecycle_stage: active
name: /Shared/Ultralytics
