DATA_PATH = "data"
DATA_SPLIT_SEED = 42
TEST_SIZE = 0.2
VAL_SIZE = 0.2
PRETRAINED_MODEL_NAME = "yolo11n.pt"
TRAIN_DATA_YAML_PATH = "data.yaml"
TRAIN_EPOCHS = 10
TRAIN_BATCH_SIZE = 8
TRAIN_LEARNING_RATE = 0.1
TRAIN_SEED = 42
TRAIN_OPTIMIZER = "Adam"
TRAIN_DEVICE = "cpu"
