artifact_location: /Users/enzobergamini/Documents/cours/tps3A/mlops/SMART-PROJECT/runs/mlflow/0
creation_time: 1739363418322
experiment_id: '0'
last_update_time: 1739363418322
lifecycle_stage: active
name: Default
